AWSTemplateFormatVersion: 2010-09-09
Description: 'Create Launch Template [created by Nirmata]'
Mappings:
  ServicePrincipalPartitionMap:
    aws:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-cn:
      EC2: ec2.amazonaws.com.cn
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-us-gov:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
Parameters:
  ClusterName:
    Type: String
    Description: Name of Cluster
  SecurityGroups:
    Type: CommaDelimitedList
    Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
Resources:
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Iops: 3000
              Throughput: 125
              VolumeSize: 80
              VolumeType: gp3
        MetadataOptions:
          HttpPutResponseHopLimit: 2
          HttpTokens: optional
        SecurityGroupIds: !Ref SecurityGroups
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${ClusterName}-nirmata-eks-karpenter-ng-Node
              - Key: karpenter.sh/discovery
                Value: !Sub ${ClusterName}
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub ${ClusterName}-nirmata-eks-karpenter-ng-Node
              - Key: karpenter.sh/discovery
                Value: !Sub ${ClusterName}
          - ResourceType: network-interface
            Tags:
              - Key: Name
                Value: !Sub ${ClusterName}-nirmata-eks-karpenter-ng-Node
              - Key: karpenter.sh/discovery
                Value: !Sub ${ClusterName}
      LaunchTemplateName: !Sub '${AWS::StackName}'
